version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    networks:
      - financialchat-internal
    environment:
      POSTGRES_DB: FinancialChatDb
      POSTGRES_USER: financialchat
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - financialchat-internal
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure

  api:
    image: nolascoacosta/financial-chat-api:latest
    networks:
      - financialchat-internal
      - nolascodenet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=FinancialChatDb;Username=financialchat;Password=${POSTGRES_PASSWORD}
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=${RABBITMQ_PASSWORD}
      - Jwt__Key=${JWT_SECRET_KEY}
      - Jwt__Issuer=financial-chat.nolascode.net
      - Jwt__Audience=FinancialChatUsers
    depends_on:
      - postgres
      - rabbitmq
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.financialchat-api.rule=Host(`financial-chat.nolascode.net`)"
        - "traefik.http.routers.financialchat-api.entrypoints=websecure"
        - "traefik.http.routers.financialchat-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.financialchat-api.loadbalancer.server.port=8080"
        - "traefik.docker.network=nolascodenet"
      restart_policy:
        condition: on-failure

  bot:
    image: nolascoacosta/financial-chat-bot:latest
    networks:
      - financialchat-internal
    environment:
      - DOTNET_ENVIRONMENT=Production
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure

networks:
  financialchat-internal:
    driver: overlay
  nolascodenet:
    external: true

volumes:
  postgres_data:
